### ISSUE TITLE
Implementing traits

### ISSUE THREAD

**Issue by JBotwina** [lgalabru/clarinet#18] opened 2021-05-01 02:52 UTC
Does Clarinet support implementing traits?

I am looking to test out this contract in Clarinet: https://explorer.stacks.co/txid/0x70c7d718cad79afd21bc0c6d562c2e100a20cdc52798b9775dda8db1d0c9de00?chain=testnet

Obviously the following line of code will not run because the current contract principal does not have a contract that implements the trait:
(use-trait tradables-trait .tradables-trait-ext.tradables-trait)
![image](https://user-images.githubusercontent.com/34082590/116768671-6ec71a80-aa06-11eb-8d28-ca0ae5ddfb0d.png)

But also, using the original address and identifier does not work:
(use-trait tradables-trait-ext 'ST33GW755MQQP6FZ58S423JJ23GBKK5ZKH3MGR55N.tradables-trait-ext )
![image](https://user-images.githubusercontent.com/34082590/116768700-9c13c880-aa06-11eb-8df4-b9ea309448a6.png)

Is there a way to resolve this?

Thanks,
James

**Comment by lgalabru** [comment] 2021-05-05 22:29
Hey @JBotwina!
Thank you for reporting that bug. The issue is coming from the fact that the Clarity LSP (≠ Clarinet) is not able to handle projects with multiple contracts. Now that Clarinet is available, the LSP should be reading the `Clarinet.toml` file, and load all the required contracts when evaluating a given contract.
This issue is already being tracked on the LSP repo, will close this one.

**Closed by lgalabru** 2021-05-05 22:29 UTC

**Comment by JBotwina** [comment] 2021-05-05 22:46
Thanks Ludo.

**Comment by JBotwina** [comment] 2021-05-06 01:54
For future reference until this issue is resolved, just add the trait to the contract you are testing.
